global using System;
global using Microsoft.AspNetCore.Authorization;
global using ActualLab.CommandR;
global using IST.Core.Entities.Auth;
global using IST.Shared.DTOs.Common;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using ActualLab.CommandR.Configuration;
global using IST.Shared.Enums;